apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bbox
  name: bbox
spec:
  volumes:
  - name: myvol
    emptyDir: {}
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: bbox
    volumeMounts:
    - name: myvol
      mountPath: /stuff
  dnsPolicy: ClusterFirst
  restartPolicy: Always
