apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bbox
  name: bbox
spec:
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: my-pvc
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: bbox
    volumeMounts:
    - name: myvol
      mountPath: /stuff
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
